//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
// </auto-generated>  
//------------------------------------------------------------------------------  

namespace Register
{
    public partial class FillingForm
    {
        protected global::System.Web.UI.WebControls.TextBox txtTenDN;
        protected global::System.Web.UI.WebControls.TextBox txtMK;
        protected global::System.Web.UI.WebControls.TextBox txtNhaplaiMK;
        protected global::System.Web.UI.WebControls.TextBox txtKH;
        protected global::System.Web.UI.WebControls.TextBox txtNgaySinh;
        protected global::System.Web.UI.WebControls.RadioButton radNam;
        protected global::System.Web.UI.WebControls.RadioButton radNu;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtThuNhap;
        protected global::System.Web.UI.WebControls.Button btnDangky;
        protected global::System.Web.UI.WebControls.Label lblThongBao;
    }
}
